services:
  postgres:
    image: postgres:17-alpine
    container_name: pharmago-db
    environment:
      POSTGRES_DB: pharmago
      POSTGRES_USER: pharmago_user
      POSTGRES_PASSWORD: pharmago_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: